/**
 * Todo Tests
 * Generated by Arc CLI
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import mongoose from 'mongoose';
import { createMinimalTestApp } from '@classytic/arc/testing';
import type { FastifyInstance } from 'fastify';
import todoResource from '../src/resources/todo/todo.resource.js';

describe('Todo Resource', () => {
  let app: FastifyInstance;

  beforeAll(async () => {
    const testDbUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/arc-app-test';
    await mongoose.connect(testDbUri);

    app = createMinimalTestApp();
    await app.register(todoResource.toPlugin());
    await app.ready();
  });

  afterAll(async () => {
    await app.close();
    await mongoose.connection.close();
  });

  describe('GET /todoes', () => {
    it('should return a list', async () => {
      const response = await app.inject({
        method: 'GET',
        url: '/todoes',
      });

      expect(response.statusCode).toBe(200);
      const body = JSON.parse(response.body);
      expect(body).toHaveProperty('docs');
    });
  });
});
