/**
 * Todo Repository
 * Generated by Arc CLI
 */

import {
  Repository,
  methodRegistryPlugin,
  softDeletePlugin,
  mongoOperationsPlugin,
} from '@classytic/mongokit';
import Todo from './todo.model.js';

class TodoRepository extends Repository {
  constructor() {
    super(Todo, [
      methodRegistryPlugin(),
      softDeletePlugin(),
      mongoOperationsPlugin(),
    ]);
  }

  /**
   * Find all active records
   */
  async findActive() {
    return this.Model.find({ isActive: true, deletedAt: null }).lean();
  }
}

const todoRepository = new TodoRepository();
export default todoRepository;
export { TodoRepository };
