/**
 * Todo Model
 * Generated by Arc CLI
 */

import mongoose, { type HydratedDocument } from 'mongoose';

const { Schema } = mongoose;

export interface ITodo {
  name: string;
  description?: string;
  isActive: boolean;
}

export type TodoDocument = HydratedDocument<ITodo>;

const todoSchema = new Schema<ITodo>(
  {
    name: { type: String, required: true, trim: true },
    description: { type: String, trim: true },
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true }
);

// Indexes
todoSchema.index({ name: 1 });
todoSchema.index({ isActive: 1 });

const Todo = mongoose.models.Todo || mongoose.model('Todo', todoSchema);
export default Todo;
