/**
 * Todo Resource
 * Generated by Arc CLI
 */

import { defineResource, createMongooseAdapter } from '@classytic/arc';
import { requireAuth } from '@classytic/arc/permissions';
import Todo, { type ITodo } from './todo.model.js';
import todoRepository from './todo.repository.js';
import { QueryParser } from '@classytic/mongokit';

const queryParser = new QueryParser();


const todoResource = defineResource<ITodo>({
  name: 'todo',
  adapter: createMongooseAdapter(Todo, todoRepository),
  queryParser,
  presets: ['softDelete'],
  permissions: {
    list: requireAuth(),
    get: requireAuth(),
    create: requireAuth(),
    update: requireAuth(),
    delete: requireAuth(),
  },
});

export default todoResource;
