/**
 * Better Auth Configuration
 * Generated by Arc CLI
 *
 * Authentication is handled entirely by Better Auth.
 * Routes are registered automatically at /api/auth/*
 *
 * Better Auth manages these collections:
 * - user, session, account
 *
 * @see https://www.better-auth.com/docs
 */

import { betterAuth } from 'better-auth';
import mongoose from 'mongoose';
import { mongodbAdapter } from 'better-auth/adapters/mongodb';
import config from '#config/index.js';

let _auth: ReturnType<typeof betterAuth> | null = null;

/**
 * Get the Better Auth instance (lazy singleton)
 *
 * Must be called AFTER database connection is established.
 */
export function getAuth(): ReturnType<typeof betterAuth> {
  if (process.env.NODE_ENV === 'production' && !process.env.BETTER_AUTH_SECRET) {
    throw new Error('BETTER_AUTH_SECRET is required in production (min 32 chars)');
  }

  if (!_auth) {
    _auth = betterAuth({
      secret: config.betterAuth.secret,
      baseURL: process.env.BETTER_AUTH_URL || `http://localhost:${config.server.port}`,
      basePath: '/api/auth',

      database: mongodbAdapter(mongoose.connection.getClient().db() as any),

      emailAndPassword: {
        enabled: true,
        minPasswordLength: 6,
      },

      // Google OAuth (enabled when env vars are set)
      ...(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET
        ? {
          socialProviders: {
            google: {
              clientId: process.env.GOOGLE_CLIENT_ID,
              clientSecret: process.env.GOOGLE_CLIENT_SECRET,
            },
          },
        }
        : {}),

      session: {
        cookieCache: {
          enabled: true,
          maxAge: 5 * 60, // 5 minutes
        },
      },

      trustedOrigins: config.frontend.urls,

      rateLimit: {
        enabled: process.env.NODE_ENV === 'production',
      },
    });
  }

  return _auth;
}

export default getAuth;
